#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please start the script as root or sudo!"
    exit 1
fi

#install ros
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install ros-indigo-desktop-full
echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
echo "Finished, please re-source your bashrc"
