#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please start the script as root or sudo!"
    exit 1
fi

./get_dependencies
./sublime_install
./opencv_install
./ros_install
./bashrc_setup
./update_gcc