#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please start the script as root or sudo!"
    exit 1
fi
sudo -y add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo -y apt-get install gcc-4.8 g++-4.8


sudo update-alternatives --remove-all gcc
sudo update-alternatives --remove-all g++
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
sudo update-alternatives --config gcc
sudo update-alternatives --config g++